---

platform: mqtt
schema: template
name: "Kitchen LEDs Right"
command_topic: "shellies/shellyrgbw2-5A3C60/color/0/set"
state_topic: "shellies/shellyrgbw2-5A3C60/color/0/status"
effect_list:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
command_on_template: >
  {"turn": "on"
  {%- if brightness is defined -%}
  , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
  {%- endif -%}
  {%- if red is defined and green is defined and blue is defined -%}
  , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
  {%- endif -%}
  {%- if white_value is defined -%}
  , "white": {{ white_value }}
  {%- endif -%}
  {%- if effect is defined -%}
  , "effect": {{ effect }}
  {%- endif -%}
  }
command_off_template: '{"turn":"off"}'
state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
red_template: '{{ value_json.red }}'
green_template: '{{ value_json.green }}'
blue_template: '{{ value_json.blue }}'
white_value_template: '{{ value_json.white }}'
effect_template: '{{ value_json.effect }}'
qos: 2
